---
- name: add rpmfusion repository
  dnf:
    name: "{{ item }}"
    state: present
    with_items:
     - "https://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-{{ dnf_releasever) }}.noarch.rpm"
     - "https://download1.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-{{ dnf_releasever }}.noarch.rpm"


- name: add Adobe repository
  dnf:
    name: "http://linuxdownload.adobe.com/adobe-release/adobe-release-{{ dnf_basearch }}-1.0-1.noarch.rpm"
    state: present

- name: add Adobe signature key
  rpm_key:
    state: present
    key: /etc/pki/rpm-gpg/RPM-GPG-KEY-adobe-linux


- name: add Google Chrome repository
  yum_repository:
    state: preesnt
    name: google-chrome
    description: Google Chrome - $basearch
    baseurl: http://dl.google.com/linux/rpm/stable/$basearch
    enabled: yes
    gpgcheck: yes
    gpgkey: https://dl-ssl.google.com/linux/linux_signing_key.pub  

#- name: add Google signature key
#  rpm_key:
#    state: present
#    key: https://dl.google.com/linux/linux_signing_key.pub


- name: add OpenH264 codec
  command: dnf config-manager --set-enabled fedora-cisco-openh264
  become: true

- name:
$ sudo dnf install gstreamer1-plugin-openh264 mozilla-openh264



- name: upgrade all packages
  dnf:
    name: "*"
    state: latest


- name: install the 'Development tools' package group
  dnf:
    name: '@Development tools'
    state: present


- name: Autoremove unneeded packages installed as dependencies
  dnf:
    autoremove: yes

- name: Uninstall httpd but keep its dependencies
  dnf:
    name: httpd
    state: absent
    autoremove: no

