---
- name: add rpmfusion free and non-free repository
  dnf:
    name: "{{ item }}"
    state: present
  with_items:
    - "https://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-{{ dnf_releasever }}.noarch.rpm"
    - "https://download1.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-{{ dnf_releasever }}.noarch.rpm"
  become: true

- name: add Adobe repository
  dnf:
    name: "http://linuxdownload.adobe.com/adobe-release/adobe-release-{{ dnf_basearch }}-1.0-1.noarch.rpm"
    state: present
  become: true

- name: add Adobe signature key
  rpm_key:
    state: present
    key: /etc/pki/rpm-gpg/RPM-GPG-KEY-adobe-linux
  become: true

- name: add Google repositories
  yum_repository:
    state: present
    file: /etc/yum.repos.d/google-{{ dnf_basearch }}.repo
    name: google-chrome-{{ item }}
    description: Google {{ item }} - $basearch
    baseurl: http://dl.google.com/linux/{{ item }}/rpm/stable/$basearch
    enabled: yes
    gpgcheck: yes
    gpgkey: https://dl-ssl.google.com/linux/linux_signing_key.pub  
  become: true
  with_item:
      - earth
      - chrome
      - mod-pagespeed

- name: enable fedora-cisco-openh246
  yum_repository:
    state: present
    file: /etc/yum.repos.d/fedora-cisco-openh264.repo
    name: fedora-cisco-openh264
    enabled: yes
  become: true

