---
- name: add rpmfusion free and non-free repository
  dnf:
    name: "{{ item }}"
    state: present
  with_items:
    - "https://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-{{ dnf_releasever }}.noarch.rpm"
    - "https://download1.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-{{ dnf_releasever }}.noarch.rpm"
  become: true

- name: add Adobe repository
  dnf:
    name: "http://linuxdownload.adobe.com/adobe-release/adobe-release-{{ dnf_basearch }}-1.0-1.noarch.rpm"
    state: present
  become: true

- name: add Adobe signature key
  rpm_key:
    state: present
    key: /etc/pki/rpm-gpg/RPM-GPG-KEY-adobe-linux
  become: true

- name: add Google base repository
  yum_repository:
    state: present
    name: google
    description: Google - $basearch
    baseurl: http://dl.google.com/linux/rpm/stable/$basearch
    enabled: yes
    gpgcheck: yes
    gpgkey: https://dl-ssl.google.com/linux/linux_signing_key.pub  
  become: true

- name: add Google Chrome repository
  yum_repository:
    state: present
    name: google-chrome
    description: Google Chrome - $basearch
    baseurl: http://dl.google.com/linux/chrome/rpm/stable/$basearch
    enabled: yes
    gpgcheck: yes
    gpgkey: https://dl-ssl.google.com/linux/linux_signing_key.pub  
  become: true

- name: add Google Earth repository
  yum_repository:
    state: present
    name: google-earth
    description: Google Earth - $basearch
    baseurl: http://dl.google.com/linux/earth/rpm/stable/$basearch
    enabled: yes
    gpgcheck: yes
    gpgkey: https://dl-ssl.google.com/linux/linux_signing_key.pub  
  become: true

- name: add OpenH264 codec repository
  command: dnf config-manager --set-enabled fedora-cisco-openh264
  become: true

