---
- name: Create Firefox extension directory
  file:
    path: "{{  ansible_env.HOME }}/.mozilla/firefox/extension"
    state: directory
    mode: 0755

- name: Install EFF Firefox plugins
  get_url:
    url: "{{ item }}"
    dest: "{{  ansible_env.HOME }}/.mozilla/firefox/extension"
  with_items:
    - https://www.eff.org/files/https-everywhere-latest.xpi
    - https://www.eff.org/files/privacy-badger-latest.xpi

