---
- lineinfile:
    path: ~/.gnupg/gpg.conf
    regexp: '^personal-digest-preferences'
    line: 'personal-digest-preferences SHA512'
- lineinfile
    path: ~/.gnupg/gpg.conf
    regexp: '^default-preference-list.*SHA512'

    #personal-digest-preferences SHA512
    #cert-digest-algo SHA512
    #default-preference-list SHA512 SHA384 SHA256 SHA224 AES256 AES192 AES CAST5 ZLIB BZIP2 ZIP Uncompressed
    #personal-cipher-preferences TWOFISH CAMELLIA256 AES 3DES
- template:


