---
- name: Create user ssh_config file
  copy:
    src: ssh_config.j2
    dest: "{{ ansible_env.HOME }}/.ssh/sshd_config"
    owner: "{{ ansible_env.USER }}"
    group: "{{ ansible_env.USER }}"
    mode: '0600'
    #validate: /usr/sbin/sshd -t -f %s
    backup: yes

- name: Create config.d directory
  file:
    path: "{{ ansible_env.HOME }}/.ssh/config.d"
    state: directory

- name: Copy config.d files to home
  copy:
    src: "{{ item }}"
    dest: "{{ ansible_env.HOME }}/.ssh/config.d/{{ item | basename }}"
    owner: "{{ ansible_env.USER }}"
    group: "{{ ansible_env.USER }}"
    mode: '0600'
    backup: no
  with_fileglob:
    - config_*

- name: Copy ssh keys to home
  copy:
    src: "{{ item }}"
    dest: "{{ ansible_env.HOME }}/.ssh/config.d/{{ item | basename }}"
    owner: "{{ ansible_env.USER }}"
    group: "{{ ansible_env.USER }}"
    mode: '0600'
    backup: no
  with_fileglob:
    - id_*



