---
- name: Install tmux package
  dnf:
    name: tmux
    state: latest
  become: yes

#- name: Install tmuxp
#  pip:
#    name: tmuxp
#    state: latest
#  when: tmux_install_tmuxp

- name: Install tpm
  git:
    repo: https://github.com/tmux-plugins/tpm
    dest: "{{ ansible_env.HOME }}/.tmux/plugins/tpm"

- name: Tmux configuration file
  template:
    src: tmux.tpl
    dest: "{{ ansible_env.HOME }}/.tmux.conf"
    force: yes
    backup: yes
    group: "{{ ansible_env.USER }}"
    owner: "{{ ansible_env.USER }}"
    mode: 0644


    i$ cd
    $ git clone https://github.com/gpakosz/.tmux.git
    $ ln -s -f .tmux/.tmux.conf
    $ cp .tmux/.tmux.conf.local .
