---
- name: Install tmux package
  dnf:
    name: tmux
    state: latest
  become: yes

#- name: Install tmuxp
#  pip:
#    name: tmuxp
#    state: latex
#  when: tmux_install_tmuxp

- name: Install tpm
  git:
    repo: https://github.com/tmux-plugins/tpm
    dest: "{{ ansible_env.HOME }}/.tmux/plugins/tpm"

- name: Change .tmux.conf
  template:
    src: tmux.tpl
    dest: "{{ ansible_env.HOME }}/.tmux.conf"
    force: yes
    backup: yes
    group: "{{ ansible_env.USER }}"
    owner: "{{ ansible_env.USER }}"
    mode: 0644

