---
- name: Install vim
  dnf:
    name: vim
    state: latest
  become: yes

- name: Install Vundle
  git:
    repo: https://github.com/VundleVim/Vundle.vim.git
    dest: ~/.vim/bundle/Vundle.vim

- name: Change .vimrc
  template:
    src: vimrc.tpl
    dest: ~/.vimrc
    force: yes
    backup: yes

#- name: install vim bundles
#  shell: vim -E -s -c "source ~/.vimrc" -c PluginInstall -c qa
#  ignore_errors: yes

