---
- name: Install vim
  dnf:
    name: vim
    state: latest
  become: yes
  when: ansible_distrubition == 'Fedora'

- name: Install vim
  apt:
    name: vim
    state: latest
    update_cach: no
  become: yes
  when: ansible_distrubition == 'Debian'

- name: Install Vundle
  git:
    repo: https://github.com/VundleVim/Vundle.vim.git
    dest: ~/.vim/bundle/Vundle.vim

- name: Change .vimrc
  template:
    src: vimrc.tpl
    dest: ~/.vimrc
    force: yes
    backup: yes

- name: install vim bundles
  shell: vim -E -s -c "source ~/.vimrc" -c PluginInstall -c qa
  ignore_errors: yes

